### ISSUE TITLE
Incorporate avrohugger's namespace mapping feature

### ISSUE THREAD

**Issue by shudas** [makubi/avrohugger-maven-plugin#14]
Avro Hugger has the ability to change the package name of the generated scala source files.
https://github.com/julianpeeters/avrohugger#customizable-namespace-mapping

Having this functionality exposed in this plugin would be great. I have created a PR to do this

https://github.com/makubi/avrohugger-maven-plugin/pull/13

**Comment by makubi** [comment]
Fixed in #15 and released in version 1.5.
