### ISSUE TITLE
Update to Avrohugger 0.15.0

### ISSUE THREAD

**Issue by mariussoutier** [makubi/avrohugger-maven-plugin#5]
Avrohugger 0.15.0 fixes ordering of AVDL files.

**Comment by julianpeeters** [comment]
Filesorter is still in sbt-avrohugger, so maybe more copy-paste for now.

**Comment by mariussoutier** [comment]
~Damn~

**Comment by mariussoutier** [comment]
But this is a good reminder that we should factor it out.

**Comment by julianpeeters** [comment]
👍
